language: python
sudo: required
dist: trusty
python:
  - "3.5"
  - "2.7"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
script:
  - py.test tests --doctest-module onix
after_success:
  - py.test
  - coveralls
