language: python
sudo: required
dist: trusty
python:
  - "3.5"
  - "2.7"
  - "3.5-dev"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
script:
  - py.test --doctest-module onix
after_success:
  - py.test --cov-config .coveragerc --cov=onix
  - coveralls
